name: registry
services:
  ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    hostname: registry-ui
    restart: always
    pull_policy: always
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=CasjaysDev Registry
      - DELETE_IMAGES=false
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=999999
    ports:
      - 172.17.0.1:59087:80
    depends_on:
      - server
    networks:
      - registry

  server:
    image: registry:latest
    container_name: registry-server
    hostname: registry-server
    restart: always
    pull_policy: always
    environment:
      - 'REGISTRY_CATALOG_MAXENTRIES=999999'
      - 'REGISTRY_STORAGE_DELETE_ENABLED=true'
      - 'REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=[*]'
      - 'REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials=[true]'
      - 'REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers=[Docker-Content-Digest]'
      - 'REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=[HEAD,GET,OPTIONS,DELETE]'
      - 'REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers=[Authorization,Accept,Cache-Control]'
    ports:
      - 172.17.0.1:59087:5000
    volumes:
      - './rootfs/data/registry:/var/lib/registry'
    networks:
      - registry

networks:
  registry:
    name: registry
    external: false
