# nginx proxy address - http://172.17.0.1:59087

name: registry
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    hostname: registry-ui
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      SINGLE_REGISTRY: "true"
      REGISTRY_TITLE: ${REGISTRY_TITLE:-Docker Registry}
      DELETE_IMAGES: ${DELETE_IMAGES:-false}
      SHOW_CONTENT_DIGEST: "true"
      NGINX_PROXY_PASS_URL: http://registry-server:5000
      SHOW_CATALOG_NB_TAGS: "true"
      CATALOG_MIN_BRANCHES: "1"
      CATALOG_MAX_BRANCHES: "1"
      TAGLIST_PAGE_SIZE: "100"
      REGISTRY_SECURED: "true"
      CATALOG_ELEMENTS_LIMIT: "999999"
      CONTAINER_NAME: registry-ui
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - 172.17.0.1:59087:80
    depends_on:
      - server
    networks:
      - registry
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://registry-ui:80'
      - 'cloudflare.hostname=registry.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.registry-ui.entrypoints=http'
      - 'traefik.http.routers.registry-ui-secure.tls=true'
      - 'traefik.http.routers.registry-ui.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.registry-ui-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.registry-ui.middlewares=registry-ui-https-redirect'
      - 'traefik.http.routers.registry-ui-secure.entrypoints=https'
      - 'traefik.http.routers.registry-ui-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.registry-ui-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.registry-ui-secure.service=registry-ui'
      - 'traefik.http.services.registry-ui.loadbalancer.server.port=80'

  server:
    image: registry:latest
    container_name: registry-server
    hostname: registry-server
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      REGISTRY_CATALOG_MAXENTRIES: "999999"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "[*]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: "[true]"
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: "[Docker-Content-Digest]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "[HEAD,GET,OPTIONS,DELETE]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "[Authorization,Accept,Cache-Control]"
      CONTAINER_NAME: registry-server
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - 172.17.0.1:5000:5000
    volumes:
      - './volumes/data/registry:/var/lib/registry'
    networks:
      - registry
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://registry-server:5000'
      - 'cloudflare.hostname=registry.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.registry-server.entrypoints=http'
      - 'traefik.http.routers.registry-server-secure.tls=true'
      - 'traefik.http.routers.registry-server.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.registry-server-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.registry-server.middlewares=registry-server-https-redirect'
      - 'traefik.http.routers.registry-server-secure.entrypoints=https'
      - 'traefik.http.routers.registry-server-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.registry-server-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.registry-server-secure.service=registry-server'
      - 'traefik.http.services.registry-server.loadbalancer.server.port=5000'

networks:
  registry:
    name: registry
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
